AWSTemplateFormatVersion: 2010-09-09
Description: >-
  shopify-bot

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        Region: 'us-east-1'

Resources:

  ConfigFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/config-handler.configHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Stores Shopify sites and Discord webhook parameters (excluding the secure API key - that is stored in Secrets Manager)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConfigTable
      Environment:
        Variables:
          # The ConfigTable stores the list of Shopify sites that the ShopifySyncFunction will check
          CONFIG_TABLE: !Ref ConfigTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /config
            Method: POST

  # This is a Lambda function config associated with the source code: get-all-items.js
  ShopifySyncFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/shopify-handler.shopifySyncHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Scans Shopify sites and writes updates to a DynamoDB table
      Policies:
          # Give Create/Read/Update/Delete Permissions to the InventoryTable
        - DynamoDBCrudPolicy:
            TableName: !Ref InventoryTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ConfigTable
      Environment:
        Variables:
          # The ConfigTable stores the list of Shopify sites that the ShopifySyncFunction will check
          CONFIG_TABLE: !Ref ConfigTable
          # The InventoryTable stores the product/stock items that were retrieved from the sites
          INVENTORY_TABLE: !Ref InventoryTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Name: ShopifySyncSchedule
            Description: Schedules the ShopifySyncFunction to run every 5 minutes
            Enabled: true
            RetryPolicy:
                MaximumEventAgeInSeconds: 86400
                MaximumRetryAttempts: 185

  # This is a Lambda function config associated with the source code: discord-handler.js
  DiscordNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/discord-handler.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 256 # 128
      Timeout: 100
      Description: Sends a Discord notification when a product is available
      Policies:
          # Give Create/Read/Update/Delete Permissions to the InventoryTable
        - DynamoDBCrudPolicy:
            TableName: !Ref InventoryTable
          # Enable Function to perform DescribeStream, GetRecords, GetShardIterator, ListStreams actions on the table
        - DynamoDBStreamReadPolicy:
            TableName: !Ref InventoryTable
            StreamName: !GetAtt InventoryTable.StreamArn
          # Enable Function to read Secret Manager store to retrieve Discord API key
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref DiscordApiKey
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          INVENTORY_TABLE: !Ref InventoryTable
          DISCORD_SECRET_ARN: !Ref DiscordApiKey
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
        StreamEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt InventoryTable.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 1
            Enabled: true
        # Uncomment the Schedule event if you would prefer to automatically run the DiscordNotificationFunction on a regular schedule
        # Schedule:
        #   Type: Schedule
        #   Properties:
        #     Schedule: rate(5 minutes)
        #     Name: DiscordNotificationSchedule
        #     Description: Schedules the DiscordNotificationFunction to run every 5 minutes
        #     Enabled: true
        #     RetryPolicy:
        #         MaximumEventAgeInSeconds: 86400
        #         MaximumRetryAttempts: 185

  ConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  InventoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  DiscordApiKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'This is the sensitive hash value that comes after "api/hooks/" in the Discord API key'
      Name: DiscordApiKey
      SecretString: '{"discord-api-key":"this-is-not-a-valid-key-please-replace"}'

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
