.PHONY: build-RuntimeDependenciesLayer

build-RuntimeDependenciesLayer:
	$(MAKE) -C $(PWD)/../app build-RuntimeDependenciesLayer ARTIFACTS_DIR=$(ARTIFACTS_DIR)

build-ConfigFunction:
	$(MAKE) -C $(PWD)/../app build-ConfigFunction ARTIFACTS_DIR=$(ARTIFACTS_DIR)

build-ShopifySyncFunction:
	$(MAKE) -C $(PWD)/../app build-ShopifySyncFunction ARTIFACTS_DIR=$(ARTIFACTS_DIR)

build-QueuePublisherFunction:
	$(MAKE) -C $(PWD)/../app build-QueuePublisherFunction ARTIFACTS_DIR=$(ARTIFACTS_DIR)

build-DiscordNotifierFunction:
	$(MAKE) -C $(PWD)/../app build-DiscordNotifierFunction ARTIFACTS_DIR=$(ARTIFACTS_DIR)
